name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.deployment.outputs.deploy_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish to Netlify
        id: deployment
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: '.'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
